# Generated by Django 4.1.2 on 2022-10-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Rating')),
                ('descritpion', models.TextField(verbose_name='Description')),
                ('cast', models.TextField(verbose_name='Cast')),
                ('poster_link', models.TextField(verbose_name='Poster link')),
                ('additional', models.TextField(verbose_name='additional')),
                ('tags', models.TextField(verbose_name='Tags')),
                ('movie_ID', models.PositiveIntegerField(verbose_name='Movie ID')),
            ],
        ),
    ]
