# Generated by Django 4.1.2 on 2022-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rating_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(null=True, verbose_name='Director'),
        ),
    ]
