# Generated by Django 4.1.2 on 2022-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_link',
            field=models.TextField(default='', verbose_name='Poster link'),
        ),
    ]
